### ISSUE TITLE
AbstractGremlinSuite assumes support for graph variables and meta properties.

### ISSUE THREAD

**Issue by pietermartin** [tinkerpop/tinkerpop3#468]
The `AbstractGremlinSuite.STRUCTURE_INTERFACES` HashSet adds `Graph.Variables.class` and `VertexProperty.Iterators.class`

This prevents the tests from executing on Sqlg.

**Comment by spmallette** [comment]
damn - sorry about that.  i miss my reflection approach to dealing with this problem.  thinking..........

**Comment by pietermartin** [comment]
np

**Comment by spmallette** [comment]
ok - i commented out those two for now.  i assume that all the graphs implement the rest of those interfaces.  i sorta wish features were statically available from the graph so that i could check them without creating an instance....perhaps i will just need to create one to throw away just so i can feature check to determine which interfaces would be present.

**Comment by spmallette** [comment]
@pietermartin hope i didn't break you again with the above commit - it checks features before making those assumptions about interfaces that *should* be present.
