### ISSUE TITLE
Support multi-valued EdgeProperty to represent dynamic Gephi graphs?

### ISSUE THREAD

**Issue by xmojmr** [tinkerpop/tinkerpop3#545]
[Gephi](https://gephi.github.io/features/) supports modeling and visualization of dynamic graphs, e.g. graphs with an edge's value changing with time. See [GEXF File Format → Dynamics](http://gexf.net/format/dynamics.html) for it's serialized representation.

In my opinion the `Tinkerpop`'s graph model should be superset of the graph models needed/used by both graph databases and graph analysis and visualization tools to be really useful standard.

Right now the `tinkerpop` proposal `3.0.0.M7` contains [Vertex Property](http://www.tinkerpop.com/docs/3.0.0.M7/#vertex-properties) concept but omits corresponding `Edge Property` concept with same capabilities.

Is it intentional? What's the recommended way to model the dynamic edges using `tinkerpop3`?

**Comment by rjbriody** [comment]
@xmojmr you might be interested in this discussion: https://github.com/tinkerpop/tinkerpop3/issues/489

**Comment by spmallette** [comment]
The choice to make properties for edges and vertices have different capabilities was intentional and has been discussed on the gremlin-users mailing list as well as various github issues since the projects inception.   @rjbriody just provided a reference to the most recent discussion on the topic.  As this discussion has been carried out in many other places, I'm going to close this issue out.  If you have other opinions to offer please take them to #489 or the new place for discussion of TinkerPop development issues now that we are an Apache Incubator project: http://mail-archives.apache.org/mod_mbox/incubator-tinkerpop-dev/ thanks
