### ISSUE TITLE
JSON serialization of ImmutablePath object is broken 

### ISSUE THREAD

**Issue by bdmcbri** [tinkerpop/tinkerpop3#587]
When executing a query that ends in .path(), a ImmutablePath object is created.  However, when serialized using JSON the result that gets returned is "[simple:true]".

**Comment by spmallette** [comment]
this should be fixed as of next release (M8) or the current SNAPSHOT - you can see the validating test here:

https://github.com/apache/incubator-tinkerpop/blob/929a2889c3ec75ff2b315200bc5abdd001bc4fcd/gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/structure/SerializationTest.java#L277

please re-open if you find otherwise.
